/**
 * OrderRail Printing Security Key Manager
 * 
 * Manages certificate and private key storage for QZ Tray request signing.
 * Auto-generated by scripts/generate-printing-cert.cjs
 */

export const ORDERRAIL_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIIDoTCCAomgAwIBAgIUfM9nEZARf1ymwzKZ7Xpg4wWQboEwDQYJKoZIhvcNAQEL
BQAwYDEiMCAGA1UEAwwZT3JkZXJSYWlsIFBPUyBDZXJ0aWZpY2F0ZTEWMBQGA1UE
CgwNT3JkZXJSYWlsIEluYzEiMCAGA1UECwwZUE9TIFByaW50aW5nIEFyY2hpdGVj
dHVyZTAeFw0yNjA3MjgxMjQxMzZaFw0zNjA3MjUxMjQxMzZaMGAxIjAgBgNVBAMM
GU9yZGVyUmFpbCBQT1MgQ2VydGlmaWNhdGUxFjAUBgNVBAoMDU9yZGVyUmFpbCBJ
bmMxIjAgBgNVBAsMGVBPUyBQcmludGluZyBBcmNoaXRlY3R1cmUwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDlI/g7x06CkskwCDocO+pwyoiLw8eaWVtO
vGIPrssM4nD+AhhRsoqZVtDbxDxyEuCmqjt/MDMddykfMbvUCbGChmp2xVssXahO
SNRf5asngoeed/yoY/KZ0xv2GDvnNHzM56dQgEwSRlpK1WAfKCqZWyQSnG4FhCzo
Ba7c9t5iI0+Cw29DUCvbQH3h8mqqJQnxWy3gxXtiJ82kxBa3fpdEScjXydT31U4P
N57Cu3XLv8RQxNeRsIW+IVZHlT/KQ3T5NneiX6I21TONDIsVsyYVGK8Kin2qeZiI
DtqZG+Uj1VBvYerPsc0BhV+lhAeiTUheB5kBTps6qhQgvRFZ35n9AgMBAAGjUzBR
MB0GA1UdDgQWBBSxrCj7zVpwOyj6ddzvKemE3TGSQzAfBgNVHSMEGDAWgBSxrCj7
zVpwOyj6ddzvKemE3TGSQzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4IBAQCqwM4P6mOQ3KXQeA/YUBI5Vdh0dhiBQCIg28uKaErR3kAU5aUd4JCWUQ3K
PNraY+C2NOdPqks6MaUPcihPR8Q3OLc4Mcb1LVQDL37yN+NLtkgveXvCL0Z38NzF
AQJx+hvdmkbcsut2WJNBFNrXEuSDustfNeVvUrEp7xGXcYhyEslzBCo4YskusI8D
QprtyIxLyYo2TNDlbeGU2TdMHmAPK5s8z8IuIFTIh79KiKev6GcB3ezhsz5Ibwsp
bJhOKq7DFqAy30OA4l0Uu1orZYXp3qU+M/tn8QYzS8p5esO3P5Rls6EE8AhaIN4c
wBiABAlWdE/J2hckDDNxq0XXk6v/
-----END CERTIFICATE-----`;

export const ORDERRAIL_PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDlI/g7x06Ckskw
CDocO+pwyoiLw8eaWVtOvGIPrssM4nD+AhhRsoqZVtDbxDxyEuCmqjt/MDMddykf
MbvUCbGChmp2xVssXahOSNRf5asngoeed/yoY/KZ0xv2GDvnNHzM56dQgEwSRlpK
1WAfKCqZWyQSnG4FhCzoBa7c9t5iI0+Cw29DUCvbQH3h8mqqJQnxWy3gxXtiJ82k
xBa3fpdEScjXydT31U4PN57Cu3XLv8RQxNeRsIW+IVZHlT/KQ3T5NneiX6I21TON
DIsVsyYVGK8Kin2qeZiIDtqZG+Uj1VBvYerPsc0BhV+lhAeiTUheB5kBTps6qhQg
vRFZ35n9AgMBAAECggEAAv+luFVnu/lHpASh1FUwHANUyx7e2Hm/4lxAU2nJGgnZ
b2hkUzlf/atK0kaTgVryUPUuopIcHtk8kuK3zVLq3WnF5wq22TtI0n8ofp40mIwg
P8q4CqfPCwQnBU7wBb97TugDvk1y8WcjSltFfK5Shq1ilq3C9WaFn6LVHg9K/d8M
Oa/9/vQgybrLQRqKZO+5OF+79Gllchk598/ob9bk5vvmDPEpR1N66LpLIR/oiOz2
+J5Zs9I2WM7V325v4g4nxsMoYJel1ei7patlLh5b2unTXVJId3GdpknWV+kWDEIc
PJjPoxIrYP38TpLPfssmjMgdKCdWFQwCiYaSQDss7wKBgQD6aE20jkGwYisnA9Rt
x4Qeg8DAVIWq30t/pw47SioJ09MST5Wq7G1ox8MsxiiR2iQCBiEk9UGsx+DYSCwC
Xr8KKREsCtxgSCCCEmRDwcaTHZJQanur+tl3Kc3rEB9qIHbNjmaJaBathEEqsSgs
rb1b2ImXwQJ5iltCpGys/Wj1twKBgQDqQhK5bEBX/q1MUrJyIr99XKU5i5cUsmsy
4XRey+rmNpgiRX3OAYrVlsAyy2r5BAehfxl2u8HtcfyS5dcTnKv5n6kJvgLBtoE6
qmHWLHgFRbKBlxoIf5CfndCvOKYZxbnUhMaw0U8LL61xXD3mdXeqMOfsk0fGk6V7
5JVeLFJN6wKBgD/wLhcyU7eT+WzG35EAZs3b2nXBnzfYOFDp+QpOj5leywBb7d1s
7SraBw4Bsw464wLZSdFEBnb1uoW/N+2K/8C6Z7YVN9wlzpcn1w4uBmQ+IsQBzH5H
WQvCUt/4h+zzSSKHf8sKFvBLWtBp19ZArp8rFUb4c4dROqgzj8REGG7VAoGAMbLy
5gPhYsnVWmvxD+XvWllddGf5FZsEwzaxyarZmx3aCOtVVW9eVRI2lJAzkcEZHVop
vNb4vbeBLmk0yCRlGACXjEmTrCVcJWYge5/TlsrCpFu6WjM2K6b/ry0FkFIyqrPA
s6K0clsbIQHA4DPrv1/A1KAqiiao5TAJwIEGtSECgYEA6OOYVcthFKBfr92deRhq
oM8VtWaceXDlKcUoGA11CiO7dtYbsSsUnPUb1boWYTdsoOGpQnsOl+dSoAQw4c8D
S3uyeAgiQF0OGeVCpbaLtqFYBBtz5VIxfh0+BT/9CA+KikqzffybRH+TwzKZ02Tl
cQ5QkvxyagzCGUPMZ177O2w=
-----END PRIVATE KEY-----`;

export const ORDERRAIL_CERT_FINGERPRINT = "88:C1:09:8E:37:78:9B:88:56:42:20:F1:0E:66:9A:9B:99:44:E4:9A:26:81:42:CA:4B:E6:B6:80:4E:37:AA:2E";

export class KeyManager {
  private static certPem = ORDERRAIL_CERTIFICATE_PEM;
  private static keyPem = ORDERRAIL_PRIVATE_KEY_PEM;
  private static certFingerprint = ORDERRAIL_CERT_FINGERPRINT;

  public static getCertificatePem(): string {
    return this.certPem;
  }

  public static getPrivateKeyPem(): string {
    return this.keyPem;
  }

  public static getFingerprint(): string {
    return this.certFingerprint;
  }

  public static isCertificateLoaded(): boolean {
    return !!(this.certPem && this.certPem.includes("CERTIFICATE"));
  }

  public static setKeys(certPem: string, privateKeyPem: string): void {
    this.certPem = certPem;
    this.keyPem = privateKeyPem;
  }
}
