/**
 * OrderRail Printing Security Key Manager
 *
 * Manages certificate and private key storage for QZ Tray request signing.
 * Auto-generated by scripts/generate-printing-cert.cjs
 *
 * NOTE (Security P1): A separate task will migrate QZ Tray digital request signing
 * to a backend/Edge Function endpoint so the private key is not bundled in client JS.
 */

export const ORDERRAIL_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIIDoTCCAomgAwIBAgIUZN5szF8vUE+qPyxqVKTpDLFnV7swDQYJKoZIhvcNAQEL
BQAwYDEiMCAGA1UEAwwZT3JkZXJSYWlsIFBPUyBDZXJ0aWZpY2F0ZTEWMBQGA1UE
CgwNT3JkZXJSYWlsIEluYzEiMCAGA1UECwwZUE9TIFByaW50aW5nIEFyY2hpdGVj
dHVyZTAeFw0yNjA3MjgxMzQ4NTFaFw0zNjA3MjUxMzQ4NTFaMGAxIjAgBgNVBAMM
GU9yZGVyUmFpbCBQT1MgQ2VydGlmaWNhdGUxFjAUBgNVBAoMDU9yZGVyUmFpbCBJ
bmMxIjAgBgNVBAsMGVBPUyBQcmludGluZyBBcmNoaXRlY3R1cmUwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC32VMm4PFq3Aq/2r1kSF5aR6roKr3bFwBv
5qN6ymKIfTYDtGAUTOtKvgigXGojtCVcuI+zsDPZ3t67oxlioAVcpMmM/a+KWUn8
ErHXDoga6yHeklKNfUTIpdlGWJCziVmSdx6/QCNXK/kidk/3PsihlpLMPXMlxNPt
pXaWsVbOh7Fzqredw+Rv50W1NEYPxqnp/S8R39jbi+gCqNHUBBDomZLvmmHbUg5Q
QzGQvg3ejYt1BsbrgP9jq99KFTlTixu+0oRef6Rgp7UQS+c5jPU9mjro2qujJwpp
+Vt5MhxCrKNYsa54edRv2R70i+9jwoR0TGzYoWI/slsbXJtcdBAfAgMBAAGjUzBR
MB0GA1UdDgQWBBSwDLggae+wNLZm2HnR3fHO533x8TAfBgNVHSMEGDAWgBSwDLgg
ae+wNLZm2HnR3fHO533x8TAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4IBAQCE2QkyOWJH6XMwN/vNtBPDsQ+bmq/FZSjMK7+FuXKL8FficuISSR7f21Te
c1LlyLY2ZlImpz1atwHmCY2TzpF5Io/5QFAhsHtF8gJEP79hZOZ9qlWwDsAq4Lab
JMIRAFO71ExrTgsiuJmrVqw/6VkdnOhGC+nrZpX4+/TDKsOESvZOM/cTJZWCnZ3m
Q+Cxp8PoKFj52R2syAK21GdIlQtYl4QRxLuDRuKAHFXd3xhxSTpryjSeJ92BtOo1
Rfc5xr/zsSAZH7IMaZanEy7x+KlApujQ66ETxOPfj9/RMxGCo5IvN+n2Bhfr6W8G
13FeTEjIyQNQB4GuVHs4Nj/v7vC0
-----END CERTIFICATE-----`;

export const ORDERRAIL_PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC32VMm4PFq3Aq/
2r1kSF5aR6roKr3bFwBv5qN6ymKIfTYDtGAUTOtKvgigXGojtCVcuI+zsDPZ3t67
oxlioAVcpMmM/a+KWUn8ErHXDoga6yHeklKNfUTIpdlGWJCziVmSdx6/QCNXK/ki
dk/3PsihlpLMPXMlxNPtpXaWsVbOh7Fzqredw+Rv50W1NEYPxqnp/S8R39jbi+gC
qNHUBBDomZLvmmHbUg5QQzGQvg3ejYt1BsbrgP9jq99KFTlTixu+0oRef6Rgp7UQ
S+c5jPU9mjro2qujJwpp+Vt5MhxCrKNYsa54edRv2R70i+9jwoR0TGzYoWI/slsb
XJtcdBAfAgMBAAECggEAVEQdqz/GF6MUoDwru6e562pW6QQSMjXYQvH1M2ZJBGNT
mx4VPajF3eO9Q3coRQYga9/CKeuU0IMpFtraW0yaOIzlPqTWTTTAxvNwpPAprSDh
zMjHYsese8UckfQtGsVVE19a7fEBYcarccLFwz75KatAzLFLsl+FfbLt6IMPFSjw
u+TlbMSGFuF1zG7FYwZgFpgonNfXfazCpCA78T8QBU6lZ+c+iZBmhS8oMa+nvAkk
+1VlSayB8Drp8U+GNmKkKfF4K2vsKXmff8y1fg88pj+lX9EQ4o8mY4hgmw1PfsEO
94hrdvzQW/QunYxzwyM5NWL8P47tvb5bLw8gli7FAQKBgQDibuWeF4GhyMrLjDmK
An0Tg/04f9jUe9rQ73DIQ9D3B7ygETtvUDs1IsnamYwVZZtD1lTsjHsaLfNq1Yzo
Oztm3tT3cT5M2vTVAmrvlZhhvLU2cZCQwEZxZtTjaf+ljj2tjBQ8wwv/3x6SKODu
0sHEqY6rIKZm58dRkmQ8izN3AQKBgQDP2vDeNiCfqarjoCof+Xdk+AMQRQptbeI4
FDrYS6Qit5rQJvjOmPSqD5Num6p7coAP/XpE10RrQJirTa3dwxwlR8eAIIeKRzxU
MrX3ETGI/KrHUoY8wedlDuWW7Zb7DpzbCt0SiR97Ih/sXR+XF6yIPN8bo1rNAoxm
omlBvZenHwKBgGj5fqxXO3r0qsfI/5fy5WeZxlheNPj1XpGEoCXIAuWziYgv1P0b
FgfhU/FrRB1bWKsPf5mW2y9c5D/ANy4m37gmUFdTAc4BqIXkNA1UriuJn/1Ykuv4
p+/E+6deqe1nz0JY8bzls/dwyix6lSVDQh/Zd9HwNhT5GVfA5YWIB1kBAoGALnAp
9Ft/emx7w5NbFf20URigBpiGNeCg9AqBAyYTK7Z9nhe26uF9eCk2tTWOJzpzph7p
nEvD+3pZIZyfRbZ7qVCaH+QkpB46Ok2CHgr3WDWrKhEj8JsZyZhEby3x13FyVfXd
YnDEWcxL+ZDsp+MgJugCqLgcZ0U0fRG4Fnn3Ud0CgYEAkaZAHxwWXs7qMdJuJ/XR
3tEOxcdNraUoZn8OWbPPOw2UkXS1phXpFnu9XAm+vLlLqfN4A7VBE/LuxcUcHQpG
VsSsn3HB84t342sr+LWc4bPFx889xx2FRMOft4XyIzhKG5yU4ap0goSvLVmAGnoS
WzN80ERIySxwQYQXux4pQbk=
-----END PRIVATE KEY-----`;

export const ORDERRAIL_CERT_FINGERPRINT = "B8:C7:7E:FF:62:A0:04:21:8E:B1:4A:04:6C:86:82:DD:BA:F3:D8:01:F1:06:5F:1E:0B:DB:81:54:ED:57:21:91";

export class KeyManager {
  private static certPem = ORDERRAIL_CERTIFICATE_PEM;
  private static keyPem = ORDERRAIL_PRIVATE_KEY_PEM;
  private static certFingerprint = ORDERRAIL_CERT_FINGERPRINT;

  public static getCertificatePem(): string {
    return this.certPem;
  }

  public static getPrivateKeyPem(): string {
    return this.keyPem;
  }

  public static getFingerprint(): string {
    return this.certFingerprint;
  }

  public static isCertificateLoaded(): boolean {
    return !!(this.certPem && this.certPem.includes("CERTIFICATE"));
  }

  public static setKeys(certPem: string, privateKeyPem: string): void {
    this.certPem = certPem;
    this.keyPem = privateKeyPem;
  }
}
