/**
 * OrderRail Printing Security Key Manager
 * 
 * Manages certificate and private key storage for QZ Tray request signing.
 * Auto-generated by scripts/generate-printing-cert.cjs
 */

export const ORDERRAIL_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwdTvMB+QjGxq/au8508cUvSzPBx0+hbMAOmeFABMwlXdA71pnhlaCaoFK0vNTt64RWr6WM7KcOt3H28c5jRZBUo0s/PuEWwt8ivE97x5sI0cRMM45Bo2u1G55dZMYzF5gDbq/eKPfktZlEycK9Nz/XsVH2VcYcrMJQc5SPcMSIHFw0kPKlMR0SMe/SqPMCuN88ZgwXaH3CHPawkNbseWHPBuGWOuWmvhjnUGXyeSrQeNJPwQwyavCtKerPWRbHs153hbdw8OWyeY05+LnUYhnmTW88jn34+DsckFu/VV19UVIwPA6OaX/KFM8A46CXc9ABkw01v8aO01gOLIda7GCQIDAQAB
-----END CERTIFICATE-----`;

export const ORDERRAIL_PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDB1O8wH5CMbGr9
q7znTxxS9LM8HHT6FswA6Z4UAEzCVd0DvWmeGVoJqgUrS81O3rhFavpYzspw63cf
bxzmNFkFSjSz8+4RbC3yK8T3vHmwjRxEwzjkGja7Ubnl1kxjMXmANur94o9+S1mU
TJwr03P9exUfZVxhyswlBzlI9wxIgcXDSQ8qUxHRIx79Ko8wK43zxmDBdofcIc9r
CQ1ux5Yc8G4ZY65aa+GOdQZfJ5KtB40k/BDDJq8K0p6s9ZFsezXneFt3Dw5bJ5jT
n4udRiGeZNbzyOffj4OxyQW79VXX1RUjA8Do5pf8oUzwDjoJdz0AGTDTW/xo7TWA
4sh1rsYJAgMBAAECggEAHpWfzEMextmQpEhF/WWhPYG5CmIfHxsbw4UZWWSWuA9e
WWm40aaEa4P1XtiOI8TG5MU1jW/Lx7ePy1j4AWb/KPOFj2ONDBi6wzyezsxhkzcg
38TCJFPykOobYCXJVdmHp3CC8d6e77mp/9l6xvuNkNCsC5Et24xpW+pg4p+Aw6vX
tvfYkV2A208Xq0QEnhmCuLvRF9eQqueUn1Ocwy6/ihFTZUWLo5EdO+tiIzHrJCEf
UOk8Xz5tEpqf1brvljxvkCS2wHHeT1lmFf0HhpOscbfE8kyP47niui+8LriqFncA
bAdjO/YGfiIg7HJuoOfKk5x0ReDNGAVJ/UOHS4RuUQKBgQD4U7hUf6gqXkKc6448
It6mOuuo6Htz1FaK9XNvyNBs7HLNvpuwyDgZP0kfXDDRaoMtG3hFcWNKrk3tiPUu
Z/+IvwtA3fydFSe4zt5zSt/fKAnZFsEPrtNCqecsMJOzfAPUNBty3iHNEd8kHM8U
JYqH7gkaErDWaevkZ1l4EVpqfQKBgQDH0idnlLUZFryv27NATxLOwx1dePYdTWBi
Kymg8ia5Rdu8j7xCKq31F3r4mUFPp3b+9/+wq5UXPwqo3QhAVJFRZgMHHHXq3mD7
PYqR6FDYZg+Rp2vzz4yv1gmMiuPaxiQ2laSEUq2PeW+F6ueJB3BYy65nvtW0Ul+P
3elaUV+TfQKBgQDFl0AdpDH3/Ga+m8PiX9CPrmRjUxEgGj3+dc2zjbMiaIX05gzV
/op8tFmHpYCGsVzNIIVzpARgoQ8KyaZllYTDl1fp9niRuQqRR7HDRTmbRC2J2kwm
IXKiIbT6+XAdKbmWORv6K3vzw5utDWtMWY7AGAyP/X1OLpvvcrjDC/PItQKBgQCa
HRnLJ8RtLz4kHDyqEtKcqZvSZeLcQrtdu5CF033OU3Tgf7NhDO3SJGPxrLHUr4J1
r+yC5DM/FJ4yExe0FgVmVFlteKPxm8YMwDBJzHXeEQlc+1WlW6RUUa5XuR93sm5n
sw6KCAJYr/41uTEOXLBnq+A9n8/PHeEaYrsBr9UZOQKBgCFsSuLfhA4n4oZ3Ibjr
A4MoH+7no2iXzVypE745btCC00ya6tCqiyNLl9eWT+4EHNs53Gzo5tuJ6nCUIwwR
Uw3hAFWVvcrOOBfgs8T4CkFQXT9pMWAkTW3HSUlttdcY3XGj87imGzNQ6ODsb0At
wW/50QWsbXYWtXR+bJlyFpeq
-----END PRIVATE KEY-----`;

export const ORDERRAIL_CERT_FINGERPRINT = "A8:50:1D:2B:AF:24:81:C0:7D:F7:7A:F7:70:BC:3E:9A:15:0D:1B:18:BC:87:B7:9E:1D:67:94:BE:F1:CC:9D:8D";

export class KeyManager {
  private static certPem = ORDERRAIL_CERTIFICATE_PEM;
  private static keyPem = ORDERRAIL_PRIVATE_KEY_PEM;
  private static certFingerprint = ORDERRAIL_CERT_FINGERPRINT;

  public static getCertificatePem(): string {
    return this.certPem;
  }

  public static getPrivateKeyPem(): string {
    return this.keyPem;
  }

  public static getFingerprint(): string {
    return this.certFingerprint;
  }

  public static isCertificateLoaded(): boolean {
    return !!(this.certPem && this.certPem.includes("CERTIFICATE"));
  }

  public static setKeys(certPem: string, privateKeyPem: string): void {
    this.certPem = certPem;
    this.keyPem = privateKeyPem;
  }
}
